/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mk4hsgrTcFL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:
//@ts-nocheck
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent } from "@/components/ui/dialog"

export function PayButton() {
  const [showModal, setShowModal] = useState(false)
  const [paymentSuccessful, setPaymentSuccessful] = useState(false)
  const handlePayNow = () => {
    setShowModal(true)
    setTimeout(() => {
      setPaymentSuccessful(true)
    }, 5000)
  }
  const handleCloseModal = () => {
    setShowModal(false)
    setPaymentSuccessful(false)
  }
  return (
    <div className="">
      {/* //flex justify-center items-center h-screen bg-background */}
      <Button
        className="bg-primary text-primary-foreground px-8 py-3 rounded-md hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        onClick={handlePayNow}
      >
        Pay Now
      </Button>
      {showModal && (
        <Dialog open={showModal} onOpenChange={handleCloseModal}>
          <DialogContent className="bg-white p-8 rounded-md shadow-lg max-w-md w-full">
            {!paymentSuccessful ? (
              <div className="flex flex-col items-center gap-4">
                <div className="bg-muted p-8 rounded-full">
                  <QrCodeIcon className="h-16 w-16 text-muted-foreground" />
                </div>
                <p className="text-lg font-medium">Scan the QR code to complete your payment</p>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-4">
                <CircleCheckIcon className="h-16 w-16 text-green-500" />
                <p className="text-lg font-medium text-green-500">Payment Successful!</p>
              </div>
            )}
          </DialogContent>
        </Dialog>
      )}
    </div>
  )
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function QrCodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="5" height="5" x="3" y="3" rx="1" />
      <rect width="5" height="5" x="16" y="3" rx="1" />
      <rect width="5" height="5" x="3" y="16" rx="1" />
      <path d="M21 16h-3a2 2 0 0 0-2 2v3" />
      <path d="M21 21v.01" />
      <path d="M12 7v3a2 2 0 0 1-2 2H7" />
      <path d="M3 12h.01" />
      <path d="M12 3h.01" />
      <path d="M12 16v.01" />
      <path d="M16 12h1" />
      <path d="M21 12v.01" />
      <path d="M12 21v-1" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
