/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IPG605L1LZz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { PayButton } from "./pay-button"

export function GarbageTax() {
  const [amount, setAmount] = useState(0)
  const gst = 0.08
  const total = 100
  return (
    <div className="w-full h-screen flex items-center  justify-center ">
    <Card className="w-[600px] h-[350px] ">
      <CardHeader>
        <CardTitle>Garbage Collection Tax Payment</CardTitle>
        <CardDescription>
          Enter the amount you owe for your garbage tax.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-1">
          {/* <Label htmlFor="amount">Taxed Amount</Label> */}
          {/* <Input
            id="amount"
            type="number"
            placeholder="Enter amount"
            value={amount}
            onChange={(e) => setAmount(parseFloat(e.target.value))}
          /> */}
        </div>
        <div className="space-y-1">
          <Label>Total Due</Label>
          <p className="text-lg font-medium">₹{total.toFixed(2)} </p>
        </div>
      </CardContent>
      <CardFooter>
        <PayButton catagory={"garbage"} amount={total} />
      </CardFooter>
    </Card>
  </div>
  )
}
